name: genblog
on: [push]
jobs:

  build:
    name: build
    runs-on: macOS-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: |
        ./release.sh
        cd blog
        ./genblog add example-article
        echo 'Hello, world!' >> articles/example-article.md
        ./genblog build
